# Generated by Django 3.1.2 on 2021-08-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redessociales',
            name='web',
            field=models.URLField(null=True, verbose_name='Web'),
        ),
    ]
